""""""""""""""""""""""""
" 2017/06/29


""""""""""""""""""""""""
" Plug

call plug#begin()

Plug 'https://github.com/scrooloose/nerdtree'
Plug 'https://github.com/itchyny/lightline.vim'

" Syntax
Plug 'https://github.com/nathanaelkane/vim-indent-guides'
Plug 'https://github.com/vim-syntastic/syntastic'
Plug 'https://github.com/cohama/lexima.vim'

" By language
Plug 'https://github.com/rust-lang/rust.vim'
Plug 'https://github.com/fatih/vim-go'
Plug 'https://github.com/leafgarland/typescript-vim'
Plug 'https://github.com/octol/vim-cpp-enhanced-highlight'
Plug 'https://github.com/justmao945/vim-clang'

call plug#end()

" vim-indent-guides setting (does not work ????)
let g:indent_guides_enable_on_vim_startup = 1
let g:indnet_guides_auto_colors=1
"hi IndentGuidesOdd  ctermbg=darkgrey
"hi IndentGuidesEven ctermbg=lightgrey

" syntastic setting
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_cpp_check_header = 1
let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = '-std=c++17 -stdlib=libc++'
let g:syntastic_cpp_checkers = ['clang']

" vim-cpp-enhanced-highlight setting
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_experimental_template_highlight = 1

" vim-clang setting
let g:clang_cpp_options = '-std=c++17 -stdlib=libc++'



""""""""""""""""""""""""
" Other cofigurations
set number
set title
filetype plugin indent on
set encoding=utf-8
syntax on
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smartindent
set hlsearch
set background=dark
set ruler
set laststatus=2
set wildmenu
nnoremap <silent><Esc><Esc> :<C-u>set nohlsearch!<CR>
set showcmd
set backspace=indent,eol,start
set scrolloff=8
set sidescrolloff=8
set cursorline
set belloff=all



"""""""""""""""""""""
" Color config
colorscheme default
hi Comment ctermfg=green
hi Statement ctermfg=yellow
hi PreProc ctermfg=cyan
hi Constant ctermfg=red
hi Type ctermfg=darkcyan



""""""""""""""""""""""""
" Filetype
autocmd BufRead,BufNewFile *.java setfiletype java




""""""""""""""""""""""""
" Local configurations
if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif


""""""""""""""""""""""""
" Local configurations
if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif

