""""""""""""""""""""""""
" 2017/06/29


""""""""""""""""""""""""
" NeoBundle

if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundle 'scrooloose/nerdtree'
NeoBundle 'nathanaelkane/vim-indent-guides'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'itchyny/lightline.vim'
NeoBundle 'cohama/lexima.vim'
NeoBundle 'rust-lang/rust.vim'
NeoBundle 'fatih/vim-go'
NeoBundle 'octol/vim-cpp-enhanced-highlight'

call neobundle#end()

colorscheme default
let g:indent_guides_enable_on_vim_startup=1
let g:indnet_guides_auto_colors=0
hi IndentGuidesOdd  guibg=grey         ctermbg=grey
hi IndentGuidesEven guibg=darkgrey     ctermbg=darkgrey

" c++
let g:syntastic_cpp_compiler_options = '-std=c++1z'





""""""""""""""""""""""""
" Other cofigurations
set number
set title
filetype plugin indent on
set encoding=utf-8
syntax on
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smartindent
set hlsearch
set background=dark
set ruler
set laststatus=2
set wildmenu
nnoremap <silent><Esc><Esc> :<C-u>set nohlsearch!<CR>
set showcmd
set backspace=indent,eol,start
set scrolloff=8
set sidescrolloff=8
set cursorline
set belloff=all




"""""""""""""""""""""
" Color config
hi Comment ctermfg=green
hi Statement ctermfg=yellow
hi PreProc ctermfg=cyan
hi Constant ctermfg=red
hi Type ctermfg=darkcyan



""""""""""""""""""""""""
" Filetype
autocmd BufRead,BufNewFile *.java setfiletype java




""""""""""""""""""""""""
" Local configurations
if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif

