""""""""""""""""""""""""
" 2017/06/29


""""""""""""""""""""""""
" NeoBundle

if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundle 'Shougo/vimproc', {
  \ 'build' : {
    \ 'windows' : 'make -f make_mingw32.mak',
    \ 'mac'     : 'make -f make_mac.mak',
    \ 'unix'    : 'make -f make_unix.mak',
  \ },
\ }
NeoBundle 'Shougo/vimshell'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'nathanaelkane/vim-indent-guides'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'itchyny/lightline.vim'
NeoBundle 'cohama/lexima.vim'

call neobundle#end()

colorscheme default
let g:indent_guides_enable_on_vim_startup=1
let g:indnet_guides_auto_colors=0
hi IndentGuidesOdd  guibg=grey         ctermbg=grey
hi IndentGuidesEven guibg=darkgrey     ctermbg=darkgrey

" c++
let g:syntastic_cpp_compiler_options = '-std=c++14'








""""""""""""""""""""""""
" Other cofigurations
set number
set title
filetype plugin indent on
set encoding=utf-8
syntax on
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smartindent
set hlsearch
set background=dark
set ruler
set laststatus=2
set wildmenu
nnoremap <silent><Esc><Esc> :<C-u>set nohlsearch!<CR>
set showcmd
set backspace=indent,eol,start



"""""""""""""""""""""
" Color config
hi Comment ctermfg=green
hi Statement ctermfg=yellow
hi PreProc ctermfg=cyan
hi Constant ctermfg=red
hi Type ctermfg=darkcyan



" ## added by OPAM user-setup for vim / base ## 93ee63e278bdfc07d1139a748ed3fff2 ## you can edit, but keep this line
let s:opam_share_dir = system("opam config var share")
let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')

let s:opam_configuration = {}

function! OpamConfOcpIndent()
  execute "set rtp^=" . s:opam_share_dir . "/ocp-indent/vim"
endfunction
let s:opam_configuration['ocp-indent'] = function('OpamConfOcpIndent')

function! OpamConfOcpIndex()
  execute "set rtp+=" . s:opam_share_dir . "/ocp-index/vim"
endfunction
let s:opam_configuration['ocp-index'] = function('OpamConfOcpIndex')

function! OpamConfMerlin()
  let l:dir = s:opam_share_dir . "/merlin/vim"
  execute "set rtp+=" . l:dir
endfunction
let s:opam_configuration['merlin'] = function('OpamConfMerlin')

let s:opam_packages = ["ocp-indent", "ocp-index", "merlin"]
let s:opam_check_cmdline = ["opam list --installed --short --safe --color=never"] + s:opam_packages
let s:opam_available_tools = split(system(join(s:opam_check_cmdline)))
for tool in s:opam_packages
  " Respect package order (merlin should be after ocp-index)
  if count(s:opam_available_tools, tool) > 0
    call s:opam_configuration[tool]()
  endif
endfor
" ## end of OPAM user-setup addition for vim / base ## keep this line




""""""""""""""""""""""""
" Filetype
autocmd BufRead,BufNewFile *.java setfiletype java


